name: docker-buildx

on:
  push:
    branches:
      - 'master'

env:
  DOCKERHUB_USER: linuxmaniac
  IMAGE_NAME: linuxmaniac/flexget
  ALPINE_VER: '3.16'

jobs:
  buildx:
    runs-on: ubuntu-20.04
    if: github.event_name != 'pull_request'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Compile requirements.txt
        run: |
          docker run --rm -i -v ${PWD}:/req alpine:${{ env.ALPINE_VER }} \
            sh -c "apk add py3-pip build-base python3-dev libffi-dev && pip install pip-tools && cd /req && pip-compile -U"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Initial Buildx
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          tags: ${{ env.IMAGE_NAME }}:testing
          platforms: linux/amd64
          build-args: |
            ALPINE_VER=${{ env.ALPINE_VER }}
      -
        name: Login to docker.io
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Buildx and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          tags: |
            ${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64
          build-args: |
            ALPINE_VER=${{ env.ALPINE_VER }}
          push: true
      -
        name: Update Dockerhub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.IMAGE_NAME }}
          short-description: ${{ steps.vars.outputs.github_desc }}
      -
        name: Commit requirements.txt
        uses: EndBug/add-and-commit@v9
        with:
          message: |
            Update requirements.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: requirements.txt
          path: requirements.txt
